/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_beldex_belnet_BelnetVPN */

#ifndef _Included_network_beldex_belnet_BelnetVPN
#define _Included_network_beldex_belnet_BelnetVPN
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_beldex_belnet_BelnetVPN
   * Method:    PacketSize
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_beldex_belnet_BelnetVPN_PacketSize(JNIEnv*, jclass);

  /*
   * Class:     network_beldex_belnet_BelnetVPN
   * Method:    Alloc
   * Signature: ()Ljava/nio/Buffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_beldex_belnet_BelnetVPN_Alloc(JNIEnv*, jclass);

  /*
   * Class:     network_beldex_belnet_BelnetVPN
   * Method:    Free
   * Signature: (Ljava/nio/Buffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_beldex_belnet_BelnetVPN_Free(JNIEnv*, jclass, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetVPN
   * Method:    Stop
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_network_beldex_belnet_BelnetVPN_Stop(JNIEnv*, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetVPN
   * Method:    ReadPkt
   * Signature: (Ljava/nio/ByteBuffer;)I
   */
  JNIEXPORT jint JNICALL
  Java_network_beldex_belnet_BelnetVPN_ReadPkt(JNIEnv*, jobject, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetVPN
   * Method:    WritePkt
   * Signature: (Ljava/nio/ByteBuffer;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_beldex_belnet_BelnetVPN_WritePkt(JNIEnv*, jobject, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetVPN
   * Method:    SetInfo
   * Signature: (Lnetwork/beldex/belnet/BelnetVPN/VPNInfo;)V
   */
  JNIEXPORT void JNICALL
  Java_network_beldex_belnet_BelnetVPN_SetInfo(JNIEnv*, jobject, jobject);
#ifdef __cplusplus
}
#endif
#endif
