/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_beldex_belnet_BelnetVPN_VPNInfo */

#ifndef _Included_network_beldex_belnet_BelnetVPN_VPNInfo
#define _Included_network_beldex_belnet_BelnetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
