/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_beldex_belnet_BelnetDaemon */

#ifndef _Included_network_beldex_belnet_BelnetDaemon
#define _Included_network_beldex_belnet_BelnetDaemon
#ifdef __cplusplus
extern "C"
{
#endif
  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    Obtain
   * Signature: ()Ljava/nio/ByteBuffer;
   */
  JNIEXPORT jobject JNICALL
  Java_network_beldex_belnet_BelnetDaemon_Obtain(JNIEnv*, jclass);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    Free
   * Signature: (Ljava/nio/ByteBuffer;)V
   */
  JNIEXPORT void JNICALL
  Java_network_beldex_belnet_BelnetDaemon_Free(JNIEnv*, jclass, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    Configure
   * Signature: (Lnetwork/beldex/belnet/BelnetConfig;)Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_beldex_belnet_BelnetDaemon_Configure(JNIEnv*, jobject, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    Mainloop
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_beldex_belnet_BelnetDaemon_Mainloop(JNIEnv*, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    IsRunning
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_beldex_belnet_BelnetDaemon_IsRunning(JNIEnv*, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    Stop
   * Signature: ()Z
   */
  JNIEXPORT jboolean JNICALL
  Java_network_beldex_belnet_BelnetDaemon_Stop(JNIEnv*, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    InjectVPNFD
   * Signature: ()V
   */
  JNIEXPORT void JNICALL
  Java_network_beldex_belnet_BelnetDaemon_InjectVPNFD(JNIEnv*, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    GetUDPSocket
   * Signature: ()I
   */
  JNIEXPORT jint JNICALL
  Java_network_beldex_belnet_BelnetDaemon_GetUDPSocket(JNIEnv*, jobject);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    DetectFreeRange
   * Signature: ()Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL
  Java_network_beldex_belnet_BelnetDaemon_DetectFreeRange(JNIEnv*, jclass);

  /*
   * Class:     network_beldex_belnet_BelnetDaemon
   * Method:    DumpStatus
   * Signature: ()Ljava/lang/String;
   */
  JNIEXPORT jstring JNICALL
  Java_network_beldex_belnet_BelnetDaemon_DumpStatus(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
